### ISSUE TITLE
有个漏洞

### ISSUE THREAD

**Issue by lifesreason** [0rangeT1ger/React-form-validator#2]
代码截图(https://cloud.githubusercontent.com/assets/1720902/16640556/81c5ddb0-442b-11e6-80f0-3ce16d4795d7.png)
最后提交验证的时候，有个缺陷，如果最后一个验证通过就通过了（前面表单项没有通过验证）
 valid (event){
        if(this.refs['vForm']){
            const rules = this.props.rules;
            let testFlag = true;
            for(let i in rules){
                if(rules.hasOwnProperty(i)){
                    let input = this.findChildInputByName(i);
                    if(input){
                        //testFlag = (this.validate(this.props.rules[i], this.props.messages[i] || {})({target: input}));此处代码
                        testFlag = (this.validate(this.props.rules[i], this.props.messages[i] || {})({target: input}))&&testFlag;
                    }
                    else {
                        throw 'ERROR: There is no input name as :' + i + ' !'
                    }
                }
            }
            if(!testFlag){
                event.preventDefault();
                event.stopPropagation();
            }
            else {
                console.log('tesssss');
                this.props.onSubmit(event);
            }
        }
        else {
            throw 'ERROR: Did not found a Form to validate. Make sure you set the ref of the Form as "vForm".'
        }
    },

**Comment by 0rangeT1ger** [comment]
已经完成了修复。
